services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun
    cap_add: [NET_ADMIN]
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${NORD_USER}
      - OPENVPN_PASSWORD=${NORD_PASS}
      - SERVER_COUNTRIES=Germany
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9999/v1/openvpn/status"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  mapillary-ts_worker:
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy

  mapillary-mk_worker:
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
